
"""
This file is auto-generated by the KeybindingConfigurator.
"""

unsorted_path = "/Users/username/path/to/unsorted/videos/"

core_buttons = {'play_pause': 'Space', 'restart': 'R', 'unsort': '0'}

folders_to_sort = {'FirstGroup': '1', 'SecondGroup': '2', 'ThirdGroup': '3', 'FourthGroup': '4', 'RemoveGroup': '9'}
